server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/account/**, /profile/**
        

        - id: catalog-service
          uri: lb://catalog-service
          predicates:
            - Path=/catalog/**

eureka:
  client:
    service-url:
     defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
